services:
  - type: web
    name: bike-rental-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bike:app"
    envVars:
      PYTHON_VERSION: 3.10
